spring.application.name=hr_pfa


# H2 Configuration
spring.datasource.url=jdbc:h2:mem:hr_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret Key (uncomment and fix syntax)
#jwt.secret=your-256-bit-base64-encoded-secret-key-here
jwt.expiration=86400000
